input_button:
  adgw_get_charge_settings_button: # button to get charge settings
    name: adgw_get_charge_settings_button
    icon: mdi:import
  adgw_set_charge_settings_button: # button to set charge settings
    name: adgw_set_charge_settings_button
    icon: mdi:export

input_select:
  adgw_battery_charge_max_soc: # battery charge max SOC
    name: adgw_battery_charge_max_soc
    icon: mdi:battery-bluetooth
    options:
      - "0"
      - "10"
      - "20"
      - "30"
      - "40"
      - "50"
      - "60"
      - "70"
      - "80"
      - "90"
      - "100"

  adgw_grid_discharge_stopped_soc: # grid discharge stopped SOC
    name: adgw_grid_discharge_stopped_soc
    icon: mdi:battery-bluetooth
    options:
      - "0"
      - "10"
      - "20"
      - "30"
      - "40"
      - "50"
      - "60"
      - "70"
      - "80"
      - "90"
      - "100"

input_datetime:
  adgw_battery_first_time_slot_1_end: # battery first, time inputs
    name: adgw_battery_first_time_slot_1_end
    icon: mdi:battery-clock
    has_date: false
    has_time: true
  adgw_battery_first_time_slot_1_start:
    name: adgw_battery_first_time_slot_1_start
    icon: mdi:battery-clock
    has_date: false
    has_time: true

  adgw_grid_first_time_slot_1_end: # grid first, time inputs
    name: adgw_grid_first_time_slot_1_end
    icon: mdi:battery-clock
    has_date: false
    has_time: true
  adgw_grid_first_time_slot_1_start:
    name: adgw_grid_first_time_slot_1_start
    icon: mdi:battery-clock
    has_date: false
    has_time: true

input_boolean:
  adgw_export_limit_on:
    name: adgw_export_limit_on
    icon: mdi:toggle-switch-outline
  adgw_ac_charge_on:
    name: adgw_ac_charge_on
    icon: mdi:toggle-switch-outline
  adgw_battery_first_time_slot_1_enabled: # switch, battery first
    name: adgw_battery_first_time_slot_1_enabled
    icon: mdi:toggle-switch-outline
  adgw_grid_first_time_slot_1_enabled: # switch, grid first
    name: adgw_grid_first_time_slot_1_enabled
    icon: mdi:toggle-switch-outline

script:
  adgw_reset_time_off_peak:
    alias: adgw_reset_time_off_peak
    sequence:
      - service: input_datetime.set_datetime
        data:
          time: "00:30:00"
        target:
          entity_id: input_datetime.adgw_battery_first_time_slot_1_start
      - service: input_datetime.set_datetime
        data:
          time: "04:30:00"
        target:
          entity_id: input_datetime.adgw_battery_first_time_slot_1_end
    mode: single
    icon: mdi:recycle-variant

  # script to stop export of electricity, can be called from Automations, eg. when power price is low
  adgw_set_export_limit_on:
    alias: adgw_set_export_limit_on
    sequence:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.adgw_export_limit_on
      - service: input_button.press
        target:
          entity_id: input_button.adgw_set_charge_settings_button
    mode: single
    icon: "mdi:toggle-switch-outline"

  # script to start export of electricity, can be called from Automations, eg. when power price is high
  adgw_set_export_limit_off:
    alias: adgw_set_export_limit_off
    sequence:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.adgw_export_limit_on
      - service: input_button.press
        target:
          entity_id: input_button.adgw_set_charge_settings_button
    mode: single
    icon: "mdi:toggle-switch-outline"

template:
  - sensor:
      - unique_id: adgw_api_state
        icon: "mdi:database"
        state: ""

homeassistant:
  # customization of elements, setting name, icons etc.
  customize:
    input_boolean.adgw_export_limit_on:
      friendly_name: Export Limit On

    # battery first
    input_select.adgw_battery_charge_max_soc:
      friendly_name: SoC Charge Max
    input_datetime.adgw_battery_first_time_slot_1_end:
      friendly_name: Battery First - Time Slot 1 (End)
    input_datetime.adgw_battery_first_time_slot_1_start:
      friendly_name: Battery First - Time Slot 1 (Start)
    input_boolean.adgw_ac_charge_on:
      friendly_name: AC Charge On
    input_boolean.adgw_battery_first_time_slot_1_enabled:
      friendly_name: Battery First - Time Slot 1 Enabled

    # grid first
    input_select.adgw_grid_discharge_stopped_soc:
      friendly_name: Discharge Stopped SoC
    input_datetime.adgw_grid_first_time_slot_1_end:
      friendly_name: Grid First - Time Slot 1 (End)
    input_datetime.adgw_grid_first_time_slot_1_start:
      friendly_name: Grid First - Time Slot 1 (Start)
    input_boolean.adgw_grid_first_time_slot_1_enabled:
      friendly_name: Grid First - Time Slot 1 Enabled

    # buttons etc
    sensor.template_adgw_api_state:
      friendly_name: API status
    input_button.adgw_get_charge_settings_button:
      friendly_name: Get charge settings from Server
    input_button.adgw_set_charge_settings_button:
      friendly_name: Set charge settings on Server
